# Generated by Django 6.0.4 on 2026-05-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversationmessage_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
